<a href="https://colab.research.google.com/github/mahmud-13797/Artificial-Intilligence/blob/main/AI_(30_7_23).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
#0-D array
arr = np.array(42)
print(arr)

42


In [ ]:
#1-D array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

[1 2 3 4 5]


In [ ]:
#2-D array
arr = np.array([[1, 2, 3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
#3-D array
import numpy as np

arr = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])
print(arr)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
#Dimension Check
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

e = np.array([[[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]], [[1,2,3],[4,5,6]]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

print(e)
print(e.ndim)


0
1
2
3
[[[[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]

  [[1 2 3]
   [4 5 6]]]]
4


In [ ]:
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]],ndmin=5)
d1 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

arr = np.array([1, 2, 3, 4], ndmin=5)

print(d)
print(d1)

print(arr)
print('number of dimensions :', d.ndim)
print('number of dimensions :', arr.ndim)

[[[[[1 2 3]
    [4 5 6]]

   [[1 2 3]
    [4 5 6]]]]]
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
[[[[[1 2 3 4]]]]]
number of dimensions : 5
number of dimensions : 5


In [ ]:
#array indexing
arr = np.array([1, 2, 3, 4])

print(arr[0])

1


In [ ]:
#array Add
arr = np.array([1, 2, 3, 4])
print(arr[2] + arr[3])

7


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr[0] + arr[3])

5


In [ ]:
#Access 2-D Array
arr = np.array([[1, 2, 3,4,5],[6,7,8,9,10]])
print(arr)
print(arr[1, 1])
print(arr[1, 4])
print(arr[0, 4])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
7
10
5


In [ ]:
#Access 3-D Array
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7,8,9], [10,11,12]]])
print(arr)
print(arr[0, 1,0])
print(arr[0, 0,2])

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
4
3


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[1:5])

[2 3 4 5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])
print(arr[1:5:2])
print(arr[::2])


arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr[1, 1:4])
print(arr[0:2, 2])
print(arr[0:2, 1:4])

[5 6 7]
[1 2 3 4]
[5 6]
[2 4]
[1 3 5 7]
[7 8 9]
[3 8]
[[2 3 4]
 [7 8 9]]


In [ ]:
arr = np.array([1, 2, 3, 4])

print(arr.dtype)

int64


In [ ]:
arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


In [ ]:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [ ]:
####
arr = np.array([1, 2, 3, 4], dtype='i4')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[1] = 42

print(arr)
print(x)

[ 1 42  3  4  5]
[ 1 42  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


In [ ]:
arr = np.array([1, 2, 3, 4, 5])

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

None
[1 2 3 4 5]


Array Shape


In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(arr.shape)

(2, 4)


In [ ]:
arr = np.array([1, 2, 3, 4,5], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4 5]]]]]
shape of array : (1, 1, 1, 1, 5)


Reshape


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
arr = np.array([1, 3, 4, 5, 6, 7, 8,9])

print(arr.reshape(2, 4).base)

[1 3 4 5 6 7 8 9]


In [ ]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


Iterating

In [ ]:
arr = np.array([0,1, 2, 3,4])

for x in arr:
  print(x)

0
1
2
3
4


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  print(x)

[1 2 3]
[4 5 6]


In [ ]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
  for y in x:
    print(y)

1
2
3
4
5
6


In [ ]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

for x in arr:
  print(x)

[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [ ]:
arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
arr1 = np.concatenate((arr1, arr2), axis=0)
print(arr)
print(arr1)

[[1 2 5 6]
 [3 4 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
arr3 = np.vstack((arr1, arr2))
print(arr)
print(arr3)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


In [ ]:
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


In [ ]:
arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


In [ ]:
arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

['apple' 'banana' 'cherry']


In [ ]:
arr = np.array([True, False, True,False,False])

print(np.sort(arr))

[False False False  True  True]


In [ ]:
arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]
